#ifndef Macro_Global_h
#define Macro_Global_h
#define KKBadge EaseUserInfoCell
#define RE3Controller WikiViewController
#define StartView TitleDisclosureCell
//#define CCCellConfig StartImagesManager
//#define HomeHeader HtmlMedia

//#define CCInfoCell LMJPicWordsViewController
//#define InfoFooter LMJScreenShotViewController

//#define ACModel MRListView
//#define UIViewController+Extension QQTimeTool
//#define START_EVENT UIMessageInputView_Media
//#define APPResult BSJTopicTopComent
//#define CategoryListModel PhoneCodeButton
#define BookChart SDWebImageOperation
//#define UIImage+Extension DynamicActivityCell
#define HomeList UIUnderlinedButton
#define BillTableCell CloudAddCell
//#define KKSocialUserInfoResponse TeamListCell
#define CategoryTable MJPhotoBrowser
#define KKEmptyCommon TweetSendTextCell
#define BookChartHUD DynamicLinksExampleUITests
#define BKCCollection ShopOrderModel
#define CategoryCell EACodeReleaseListViewController
#define ChartTableHeader LMJWebViewController
#define BDController FileCommentCell
//#define WebVC MBProgressHUD
//#define BKCController TaskResourceReferenceCell
//#define UIView+SyncedData TagCCell
//#define NSString+Calculation CrashReportingExampleUITests
//#define UIView+Visuals VIDTableViewController
#define ChartHUD SINPublishToolBar
//#define ACAListModel WPFAttachmentView
//#define BD_EVENT AddMDCommentViewController
//#define StartScroll MJDownloadConst
//#define TIController EACodeReleaseTopCell
#define FindBookCell BSJMeViewController
#define ACATextField BSJTopicVideoView
//#define BaseTableCellProtocol LMJBaseResponse
//#define CCTableView NeteaseMusicAPI
//#define AboutController PresentAnimator
//#define BDHeader EaseMarkdownTextView
//#define BaseNavigationController+Extension SINBroswerViewController
//#define JHCollectionViewLayoutAttributes MRPRFilesViewController
//#define KKEmptyPch CodeViewController
//#define YYLabel+Extension LMJMessageViewController
//#define UIView+BlockGesture interf_enc
//#define MineHeader DirectoryWatcher
#define StartKeyboard ShopOrderListView
//#define UIViewController+UMengExtension EACodeBranches
//#define CPAController ActivityView
//#define StartScrollCell TeamPurchaseTopCell
//#define PhoneController TaskComment
//#define ChartDateCell Close2FAViewController
//#define CountDown Helper
//#define MineTableCell CSTopicCreateVC
//#define FindFeatureCell LMJItemSection
//#define common ProjectTopicActivity
//#define RequestTipRefreshFooter LMJChildBlockViewController
#define RE2Controller LogWrapper
//#define BillController DWAmountViewController
#define KKGoodsEmpty CSSearchDisplayVC
//#define JHCollectionReusableView ListGroupItem
//#define UIButton+BarButtonItem DownloadViewController
//#define ASBaseTableCell HOTPGenerator
//#define ChartHUDCell LMJHorizontalFlowLayout
//#define UICollectionReusableView+Extension OTPGenerator
//#define TIModel CommitCommentCell
//#define MineFooterView DWSendViewController
//#define BKCNavigation UIVerticalAlignmentLabel
//#define BKCRefreshHeader LMJNavBarFadeViewController
//#define BKCCollectionCell TweetSendDetailLoctionCell
//#define BaseTableCell DES3Encryptor
//#define BKCKeyboard QcTask
//#define BaseCollectionView AllSearchDisplayVC
//#define InfoTableView MRPRTopCell
//#define HomeListSubCell AdvertiseView
//#define HomeListCell RDVTabBarItem
//#define ZLPhotoActionSheet+Extension SINStatusListService
//#define NSString+Encryption TaskDescriptionCell
//#define UIViewController+APPViewRequest Project_RootViewController
//#define ACCellMode FileChangeListCell
#define KKEmptyNoNet WatchApp
//#define ShareOrder FBShimmering
//#define UIResponder+QFEventHandle BaseModel
//#define UIView+JGProgressHUD LMJPiesViewController
//#define UIViewController+KKEmpty LMJRequestBaseViewController
//#define MineTableHeader BubblePlayView
//#define ChartTableView CountryCodeListViewController
//#define KKRefreshNormalHeader ProjectCodeListSearchCell
//#define ChartDate Route
//#define BaseTabBarController LMJZDTPViewController
//#define CCReplyCell LMJDrawStrPicsViewController
//#define TIMING_EVENT MeRootCompanyCell
//#define UICollectionView+Extension AFURLConnectionOperation
//#define BaseCollectionReusableView TopicAnswerCommentMoreCell
//#define AppDelegate WPFSpringView
//#define UIView+KKEmpty LeftImage_LRTextCell
//#define CAHeader EACodeReleaseViewController
//#define InfoTableCell DWAmountInputValidator
//#define APPViewRequest AnalyticsExampleUITests
//#define UserInfo GlowImageView
//#define UIWindow+JGProgressHUD WKWebViewJsBridge
//#define BaseModel EaseStartView
//#define CHART_EVENT MeDisplayViewController
//#define ChartSegmentControl SettingSkillsViewController
//#define UIImage+BlurGlass SINPostStatusService
//#define BottomButton XHRealTimeBlur
//#define BaseTabBar SINStatusListDAL
//#define ACAReusableHeader LMJElementsCollectionViewController
//#define KKPopup SINUserManager
//#define ContentView TeamPurchaseBillingDetail
//#define StartHeader AbstractActionSheetPicker
//#define CAController AFNetworkReachabilityManager
//#define BadgeCollection LMJOCJSHelper
//#define CCController ValueListCell
//#define BaseTableView EACodeBranchListCell
//#define BadgeReusableHeader MeRootUserCell
//#define BaseService EACodeBranchListViewController
//#define INFO_EVENT_MANAGER TweetCell
//#define LoginController Projects
//#define MineTableView BSJTopicViewModel
//#define UIView+BorderLine TaskBoardsViewController
//#define NSAttributedString+Extension AFURLResponseSerialization
//#define BaseCollectionCell LMJCAAnimationGroupViewController
//#define ACACollection LMJRefreshTableViewController
//#define BDBottom BRTxInputEntity
//#define UITableView+Extension PointRecordsViewController
//#define BCHUDContentCell UICustomCollectionView
//#define AFNManager CSSearchVC
//#define HOME_EVENT LMJCATransitionViewController
//#define BCHUDContent NProjectFileListView
//#define MINE_EVENT_MANAGER SkillCCell
//#define NSString+API TitleValueCell
//#define ACACollectionCell LMJNewViewController
//#define LOGIN_NOTIFICATION EAFliterMenu
//#define MineController BSJComment
//#define UIView+APPViewRequest TaskActivityCell
//#define UIScrollView+Extension DSWatchTransactionDataObject
//#define HomeListEmpty SINStatus
//#define UIColor+HEX ProjectTagLabel
//#define BadgeReusableFooter TopicSearchCell
//#define BDTableCell DWRootViewController
//#define BaseView EaseToolBar
//#define BadgeController MRDetailViewController
//#define BillTable DWStoryboardSegueWithCompletion
#define BadgeCollectionCell ResetLabelViewController
//#define NSObject+NSCoding LMJListExpandHideViewController
//#define ACA_EVENT_MANAGER TweetSendLocaitonMapViewController
//#define HomeNavigation BRBouncyBurgerButton
//#define MineView ASPopUpView
#define JHCollectionViewFlowLayout CodeFile
//#define CategorySectionHeader WKWebViewJsBridge.temp_caseinsensitive_rename
//#define UIView+Extension CommitListCell
//#define HomeListHeader UserActiveStatusView
//#define RE1Controller LMJAutoRefreshFooter
//#define ChartTableCell LMJCALayerBaseViewController
//#define ChartNavigation MUSHomeListViewController
//#define FindController CodingSearchDisplayView
//#define MonthController LMJBlockLoopViewController
//#define ChartSectionHeader LMJXueHuaViewController
//#define CCModel BSJTrendViewController
//#define NSMutableArray+Extension ShopMutileValueCell
//#define ShareBottom MessageCell
//#define KKEmptyLoading ParamTableViewCell
//#define InfoController AddUserViewController
//#define BaseNavigationController LMJHDZSQViewController
//#define ChartSubModel CSScrollview
//#define BaseViewController FileComment
//#define ShareShot BSJRecommendCategory
//#define NSString+Extension TopicCommentCCell
//#define UIFont+Extension UserInfoDetailViewController
#define BillHeader Login
//#define BadgeListModel SettingEmailViewController
#define ShareBadge TeamMember
//#define ScreenBlurry NJKWebViewProgressView
//#define BOOK_EVENT Me_RootViewController
//#define NSUserDefaults+Extension ResetLabelCell
//#define ChartController SDWebImagePrefetcher
//#define KKRefreshNormalFooter DWSeedViewController
//#define CCActionCell ProjectArchiveViewController
//#define UITableViewCell+Extension LMJHandleView
//#define BaseViewController+Extension DWGenerateViewController
//#define NSObject+JGRuntime BSJMeSquareCell
//#define BKModel SettingTagsViewController
//#define BaseView+Popup TeamPurchaseBillingCell
#define KKEmptyNoneOrder QBAlbumsViewController
//#define BookPunch XGPush
//#define ShareController CommitFilesViewController
//#define ASBaseViewController CategorySearchBar
//#define Common UIMessageInputView
//#define CCIconCell ProjectTopicListView
//#define UserModel PointTopCell
//#define ACTableNode TopicPreviewCell
//#define CA_EVENT ShopOderCell
//#define CALayer+Extension LMJBlankPageViewController
#define PINCache_Header DWWhiteActionButton
//#define UIViewController+JGProgressHUD LMJAutoLayoutViewController
//#define ACAController ProjectInfoCell
//#define BDTable LMJBlockLoopOperation
//#define BKCIncomeModel MCCoreDataManager
//#define AppDelegate+UMeng BSJUser
#define TITableView FileEditViewController
#define BaseCollectionCellProtocol LocalFolderCell
#define Single JDStatusBarNotification
#define ACController AboutPointViewController
//#define KKEmpty LMJUniversalLinkViewController
//#define HomeController AppDelegate
//#define TITableCell FRDLivelyButton
//#define NSDate+Extension CommentCell
//#define KKRefreshGifHeader LMJElementsFlowLayout
#endif
